### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by mmulich** [ilikerobots/django-vue-utilities#2]
Something in setuptools must have changed. The installation of this package no longer works. The following illustrates this error.

```
$ docker run --rm -it python:3.10 bash
root@42fe5bddf6e6:/# pip install django-vue-utils
Collecting django-vue-utils
  Downloading django-vue-utils-0.1.8.tar.gz (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 76.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      /tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:71: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `license = 'MIT'`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `license` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table

              To prevent this problem, you can list `license` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:71: _MissingDynamic: `dependencies` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `dependencies = ['Django >= 3.2']`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `dependencies` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table

              To prevent this problem, you can list `dependencies` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 647, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 72, in apply_configuration
          return _apply(dist, config, filepath)
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 52, in apply
          _apply_project_table(dist, config, root_dir)
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 78, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-dfzf8ko8/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 181, in _license
          _set_config(dist, "license", val["text"])
      KeyError: 'text'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by mmulich** [comment]
Also, there seems to be a discrepancy between the committed version and the released version. The `pyproject.toml` shows version `v0.1.7`, but the released version is `v0.1.8`.
